import numpy as np

vetor1 = np.array([1, 2, 3, 4, 5])
vetor2 = np.array([2, 3, 4, 5, 6])
zeros = np.zeros(shape=(2, 2))
a = np.ones(shape=(1, 2))
# b = np.arange(shape=(1, 1))
c = np.empty(shape=(1, 1))
d = np.size(1)
# aa = np.ndim()
# bb = np.shape()
# e = np.linespace(1)
print("array:", vetor1)
print("zeros:", zeros.shape)
print("ones:", a)
# print("arange:", b)
print("empty", c)
a12 = np.concatenate(vetor1, vetor2)
print(a12)
